apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  labls:
    app: myapp
spec:
  replicas: 2
  selector:
      matchLabels:
          app: myapp
          version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
        - name: myapp
          image: hub.docker.com/repository/docker/dalpengholic/devops_capstone_blue
          imagePullPolicy: Always
          ports:
            - containerPort: 80
  
